# https://dart-lang.github.io/linter/lints/
linter:
  rules:
    - avoid_init_to_null
    - camel_case_extensions
    - camel_case_types
    - non_constant_identifier_names
    - only_throw_errors
    - prefer_final_locals
    - prefer_single_quotes
    - unawaited_futures
    - library_names
    - file_names
    - curly_braces_in_flow_control_structures
    - slash_for_doc_comments
    - package_api_docs
    - comment_references
    - avoid_relative_lib_imports
    - prefer_adjacent_string_concatenation
    - prefer_interpolation_to_compose_strings
    - unnecessary_brace_in_string_interps
    - prefer_collection_literals
    - avoid_function_literals_in_foreach_calls
    - prefer_iterable_whereType
    - prefer_function_declarations_over_variables
    - unnecessary_lambdas
    - prefer_equal_for_default_values
    - unnecessary_getters_setters
    - unnecessary_this
    - prefer_initializing_formals
    - type_init_formals
    - empty_constructor_bodies
    - unnecessary_new
    - unnecessary_const
    - use_rethrow_when_possible
    - use_to_and_as_if_applicable
    - prefer_final_fields
    - use_setters_to_change_properties
    - avoid_setters_without_getters
    - avoid_returning_this
    - prefer_typing_uninitialized_variables
    - omit_local_variable_types
    - avoid_return_types_on_setters
    - prefer_generic_function_type_aliases
    - avoid_private_typedef_functions
    - use_function_type_syntax_for_parameters
    - hash_and_equals
    - avoid_null_checks_in_equality_operators
    - always_declare_return_types
    - prefer_const_declarations
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - unnecessary_await_in_return
    - await_only_futures
    - avoid_void_async