name: treasure_of_the_high_seas
description: Arrrr

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  meta: 1.3.0
  provider: ^5.0.0
  flutter_swiper: 1.1.6
  shared_preferences: 0.5.12+4
  audioplayers: ^0.17.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.8.1
  mockito: ^4.1.4
  matcher: 0.12.10

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/skull_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/text/
    - assets/music/
    - assets/sfx/
  fonts:
    - family: TreasureHunt
      fonts:
        - asset: assets/fonts/Treasurehunt-DOYwE.ttf